# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  generate-grpc:
    cmds:
      - protoc --proto_path=proto --go_out=internal --go_opt=paths=source_relative --go-grpc_out=internal --go-grpc_opt=paths=source_relative proto/block.proto proto/player.proto proto/auth.proto
    silent: false
  start-server:
    cmds:
      - go run cmd/server/main.go
